import {createApp} from 'vue'
import App from './App.vue'
import PrimeVue from 'primevue/config';
import DataTable from "primevue/datatable";
import Column from "primevue/column";
import 'primevue/resources/themes/md-dark-deeppurple/theme.css';
import "primeflex/primeflex.css";
import 'primeicons/primeicons.css';
import InputText from "primevue/inputtext";
import Button from "primevue/button";
import Divider from "primevue/divider";
import TabView from "primevue/tabview";
import TabPanel from "primevue/tabpanel";
import Timeline from "primevue/timeline";
import Card from "primevue/card";
import Accordion from "primevue/accordion";
import AccordionTab from "primevue/accordiontab";
import ToastService from 'primevue/toastservice';
import ConfirmationService from 'primevue/confirmationservice';
import Toast from "primevue/toast";
import ProgressBar from "primevue/progressbar";
import Badge from "primevue/badge";
import FileUpload from "primevue/fileupload";
import Tooltip from "primevue/tooltip";
import ConfirmPopup from "primevue/confirmpopup";
import Steps from "primevue/steps";
import Textarea from "primevue/textarea";
import ProgressSpinner from "primevue/progressspinner";
import Sidebar from "primevue/sidebar";
import Avatar from "primevue/avatar";
import Ripple from "primevue/ripple";
import StyleClass from "primevue/styleclass";
import SpeedDial from "primevue/speeddial";
import ConfirmDialog from "primevue/confirmdialog";
import SplitButton from "primevue/splitbutton";

const app = createApp(App);
app.use(ToastService);
app.use(ConfirmationService);
app.use(PrimeVue, {ripple: true});
app.component('DataTable', DataTable);
app.component('Column', Column);
app.component('InputText', InputText);
app.component('Button', Button);
app.component('Divider', Divider);
app.component('Tabview', TabView);
app.component('Tabpanel', TabPanel);
app.component('Timeline', Timeline);
app.component('Card', Card);
app.component('Accordion', Accordion);
app.component('AccordionTab', AccordionTab);
app.component('Toast', Toast);
app.component('ProgressBar', ProgressBar);
app.component('Badge', Badge);
app.component('FileUpload', FileUpload);
app.component('ConfirmPopup', ConfirmPopup);
app.component('Steps', Steps);
app.component('Textarea', Textarea);
app.component('ProgressSpinner', ProgressSpinner);
app.component('Sidebar', Sidebar);
app.component('Avatar', Avatar);
app.component('SpeedDial', SpeedDial);
app.component('ConfirmDialog', ConfirmDialog);
app.component('SplitButton', SplitButton);
app.directive('tooltip', Tooltip);
app.directive('ripple', Ripple);
app.directive('styleclass', StyleClass);
app.mount('#app');